### ISSUE TITLE
Code review per request

### ISSUE THREAD

**Issue by StoneCypher** [ellowrath/ClangMan#6]
[On Reddit you requested a code review](https://www.reddit.com/r/C_Programming/comments/kw4f98/review_my_hangman_if_youre_bored/).  

I'm opening some issues, and I'll track them here as I go.

Here are a few places to start.  If you fix these and enjoyed this, tag me when you're done, and I'll open more.

* [ ] #7 Defines as constants
* [x] #8 returning bool from everything
* [ ] #9 Too much decomposition
* [ ] #10 Obscure variable names
* [ ] #11 Are you ... is this efficiency optimization?
* [ ] #12 Why are the words on the filesystem?
* [ ] #13 What is set_word_by_line_num doing?
* [ ] #14 Not enough decomposition
* [ ] #15 Word reading code is too tricky by triple
* [ ] #16 Extremely verbose style
* [ ] #17 re-implementing standard library functions

**Comment by ellowrath** [comment]
Thank you!  I'm going through and fixing things.  I really appreciate the help.

**Comment by StoneCypher** [comment]
Cool.  I was worried; some people would have disliked this level of detail.

**Comment by StoneCypher** [comment]
You can check these boxes off, and not only will the meter go up, but you will probably achieve some satisfaction from seeing it happen

Just click, no need to edit the text.

**Comment by StoneCypher** [comment]
I checked #8 for you to make it more obvious that those are checkboxes

**Comment by ellowrath** [comment]
Sweet. I was not aware.
